name: ci

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest

      - name: test
        run: go test -short -race -cover ./...

      - name: build
        run: go build -o vsenv.exe .
